//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QLChuyenBayVaVeMayBayModel", "FK_ChuyenBay_HangTrinh", "HangTrinh", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QL_ChuyenBay.HangTrinh), "ChuyenBay", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QL_ChuyenBay.ChuyenBay), true)]
[assembly: EdmRelationshipAttribute("QLChuyenBayVaVeMayBayModel", "FK_ChuyenBay_MayBay", "MayBay", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QL_ChuyenBay.MayBay), "ChuyenBay", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QL_ChuyenBay.ChuyenBay), true)]
[assembly: EdmRelationshipAttribute("QLChuyenBayVaVeMayBayModel", "FK_Ve_ChuyenBay", "ChuyenBay", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QL_ChuyenBay.ChuyenBay), "Ve", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QL_ChuyenBay.Ve), true)]
[assembly: EdmRelationshipAttribute("QLChuyenBayVaVeMayBayModel", "FK_DoiTraVe_Ve", "Ve", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QL_ChuyenBay.Ve), "DoiTraVe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QL_ChuyenBay.DoiTraVe), true)]
[assembly: EdmRelationshipAttribute("QLChuyenBayVaVeMayBayModel", "FK_Ve_HanhKhach", "HanhKhach", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QL_ChuyenBay.HanhKhach), "Ve", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QL_ChuyenBay.Ve), true)]
[assembly: EdmRelationshipAttribute("QLChuyenBayVaVeMayBayModel", "FK_LichBay_MayBay", "MayBay", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QL_ChuyenBay.MayBay), "LichBay", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QL_ChuyenBay.LichBay), true)]

#endregion

namespace QL_ChuyenBay
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QLChuyenBayVaVeMayBayEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QLChuyenBayVaVeMayBayEntities object using the connection string found in the 'QLChuyenBayVaVeMayBayEntities' section of the application configuration file.
        /// </summary>
        public QLChuyenBayVaVeMayBayEntities() : base("name=QLChuyenBayVaVeMayBayEntities", "QLChuyenBayVaVeMayBayEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLChuyenBayVaVeMayBayEntities object.
        /// </summary>
        public QLChuyenBayVaVeMayBayEntities(string connectionString) : base(connectionString, "QLChuyenBayVaVeMayBayEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLChuyenBayVaVeMayBayEntities object.
        /// </summary>
        public QLChuyenBayVaVeMayBayEntities(EntityConnection connection) : base(connection, "QLChuyenBayVaVeMayBayEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ChuyenBay> ChuyenBays
        {
            get
            {
                if ((_ChuyenBays == null))
                {
                    _ChuyenBays = base.CreateObjectSet<ChuyenBay>("ChuyenBays");
                }
                return _ChuyenBays;
            }
        }
        private ObjectSet<ChuyenBay> _ChuyenBays;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DoiTraVe> DoiTraVes
        {
            get
            {
                if ((_DoiTraVes == null))
                {
                    _DoiTraVes = base.CreateObjectSet<DoiTraVe>("DoiTraVes");
                }
                return _DoiTraVes;
            }
        }
        private ObjectSet<DoiTraVe> _DoiTraVes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HangTrinh> HangTrinhs
        {
            get
            {
                if ((_HangTrinhs == null))
                {
                    _HangTrinhs = base.CreateObjectSet<HangTrinh>("HangTrinhs");
                }
                return _HangTrinhs;
            }
        }
        private ObjectSet<HangTrinh> _HangTrinhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HanhKhach> HanhKhaches
        {
            get
            {
                if ((_HanhKhaches == null))
                {
                    _HanhKhaches = base.CreateObjectSet<HanhKhach>("HanhKhaches");
                }
                return _HanhKhaches;
            }
        }
        private ObjectSet<HanhKhach> _HanhKhaches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LichBay> LichBays
        {
            get
            {
                if ((_LichBays == null))
                {
                    _LichBays = base.CreateObjectSet<LichBay>("LichBays");
                }
                return _LichBays;
            }
        }
        private ObjectSet<LichBay> _LichBays;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MayBay> MayBays
        {
            get
            {
                if ((_MayBays == null))
                {
                    _MayBays = base.CreateObjectSet<MayBay>("MayBays");
                }
                return _MayBays;
            }
        }
        private ObjectSet<MayBay> _MayBays;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ve> Ves
        {
            get
            {
                if ((_Ves == null))
                {
                    _Ves = base.CreateObjectSet<Ve>("Ves");
                }
                return _Ves;
            }
        }
        private ObjectSet<Ve> _Ves;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChuyenBays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChuyenBays(ChuyenBay chuyenBay)
        {
            base.AddObject("ChuyenBays", chuyenBay);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DoiTraVes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDoiTraVes(DoiTraVe doiTraVe)
        {
            base.AddObject("DoiTraVes", doiTraVe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HangTrinhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHangTrinhs(HangTrinh hangTrinh)
        {
            base.AddObject("HangTrinhs", hangTrinh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HanhKhaches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHanhKhaches(HanhKhach hanhKhach)
        {
            base.AddObject("HanhKhaches", hanhKhach);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LichBays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLichBays(LichBay lichBay)
        {
            base.AddObject("LichBays", lichBay);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MayBays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMayBays(MayBay mayBay)
        {
            base.AddObject("MayBays", mayBay);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ves EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVes(Ve ve)
        {
            base.AddObject("Ves", ve);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLChuyenBayVaVeMayBayModel", Name="ChuyenBay")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChuyenBay : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ChuyenBay object.
        /// </summary>
        /// <param name="maCB">Initial value of the MaCB property.</param>
        /// <param name="maHT">Initial value of the MaHT property.</param>
        /// <param name="maMB">Initial value of the MaMB property.</param>
        public static ChuyenBay CreateChuyenBay(global::System.String maCB, global::System.String maHT, global::System.String maMB)
        {
            ChuyenBay chuyenBay = new ChuyenBay();
            chuyenBay.MaCB = maCB;
            chuyenBay.MaHT = maHT;
            chuyenBay.MaMB = maMB;
            return chuyenBay;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaCB
        {
            get
            {
                return _MaCB;
            }
            set
            {
                if (_MaCB != value)
                {
                    OnMaCBChanging(value);
                    ReportPropertyChanging("MaCB");
                    _MaCB = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaCB");
                    OnMaCBChanged();
                }
            }
        }
        private global::System.String _MaCB;
        partial void OnMaCBChanging(global::System.String value);
        partial void OnMaCBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaHT
        {
            get
            {
                return _MaHT;
            }
            set
            {
                OnMaHTChanging(value);
                ReportPropertyChanging("MaHT");
                _MaHT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaHT");
                OnMaHTChanged();
            }
        }
        private global::System.String _MaHT;
        partial void OnMaHTChanging(global::System.String value);
        partial void OnMaHTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaMB
        {
            get
            {
                return _MaMB;
            }
            set
            {
                OnMaMBChanging(value);
                ReportPropertyChanging("MaMB");
                _MaMB = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaMB");
                OnMaMBChanged();
            }
        }
        private global::System.String _MaMB;
        partial void OnMaMBChanging(global::System.String value);
        partial void OnMaMBChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_ChuyenBay_HangTrinh", "HangTrinh")]
        public HangTrinh HangTrinh
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HangTrinh>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_HangTrinh", "HangTrinh").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HangTrinh>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_HangTrinh", "HangTrinh").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HangTrinh> HangTrinhReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HangTrinh>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_HangTrinh", "HangTrinh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HangTrinh>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_HangTrinh", "HangTrinh", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_ChuyenBay_MayBay", "MayBay")]
        public MayBay MayBay
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MayBay>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_MayBay", "MayBay").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MayBay>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_MayBay", "MayBay").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MayBay> MayBayReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MayBay>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_MayBay", "MayBay");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MayBay>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_MayBay", "MayBay", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_Ve_ChuyenBay", "Ve")]
        public EntityCollection<Ve> Ves
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ve>("QLChuyenBayVaVeMayBayModel.FK_Ve_ChuyenBay", "Ve");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ve>("QLChuyenBayVaVeMayBayModel.FK_Ve_ChuyenBay", "Ve", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLChuyenBayVaVeMayBayModel", Name="DoiTraVe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DoiTraVe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DoiTraVe object.
        /// </summary>
        /// <param name="maLP">Initial value of the MaLP property.</param>
        /// <param name="maVe">Initial value of the MaVe property.</param>
        /// <param name="lePhi">Initial value of the LePhi property.</param>
        public static DoiTraVe CreateDoiTraVe(global::System.String maLP, global::System.String maVe, global::System.Decimal lePhi)
        {
            DoiTraVe doiTraVe = new DoiTraVe();
            doiTraVe.MaLP = maLP;
            doiTraVe.MaVe = maVe;
            doiTraVe.LePhi = lePhi;
            return doiTraVe;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaLP
        {
            get
            {
                return _MaLP;
            }
            set
            {
                if (_MaLP != value)
                {
                    OnMaLPChanging(value);
                    ReportPropertyChanging("MaLP");
                    _MaLP = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaLP");
                    OnMaLPChanged();
                }
            }
        }
        private global::System.String _MaLP;
        partial void OnMaLPChanging(global::System.String value);
        partial void OnMaLPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaVe
        {
            get
            {
                return _MaVe;
            }
            set
            {
                OnMaVeChanging(value);
                ReportPropertyChanging("MaVe");
                _MaVe = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaVe");
                OnMaVeChanged();
            }
        }
        private global::System.String _MaVe;
        partial void OnMaVeChanging(global::System.String value);
        partial void OnMaVeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LePhi
        {
            get
            {
                return _LePhi;
            }
            set
            {
                OnLePhiChanging(value);
                ReportPropertyChanging("LePhi");
                _LePhi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LePhi");
                OnLePhiChanged();
            }
        }
        private global::System.Decimal _LePhi;
        partial void OnLePhiChanging(global::System.Decimal value);
        partial void OnLePhiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_DoiTraVe_Ve", "Ve")]
        public Ve Ve
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ve>("QLChuyenBayVaVeMayBayModel.FK_DoiTraVe_Ve", "Ve").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ve>("QLChuyenBayVaVeMayBayModel.FK_DoiTraVe_Ve", "Ve").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ve> VeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ve>("QLChuyenBayVaVeMayBayModel.FK_DoiTraVe_Ve", "Ve");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ve>("QLChuyenBayVaVeMayBayModel.FK_DoiTraVe_Ve", "Ve", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLChuyenBayVaVeMayBayModel", Name="HangTrinh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HangTrinh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HangTrinh object.
        /// </summary>
        /// <param name="maHT">Initial value of the MaHT property.</param>
        /// <param name="diemDi">Initial value of the DiemDi property.</param>
        /// <param name="diemDen">Initial value of the DiemDen property.</param>
        public static HangTrinh CreateHangTrinh(global::System.String maHT, global::System.String diemDi, global::System.String diemDen)
        {
            HangTrinh hangTrinh = new HangTrinh();
            hangTrinh.MaHT = maHT;
            hangTrinh.DiemDi = diemDi;
            hangTrinh.DiemDen = diemDen;
            return hangTrinh;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaHT
        {
            get
            {
                return _MaHT;
            }
            set
            {
                if (_MaHT != value)
                {
                    OnMaHTChanging(value);
                    ReportPropertyChanging("MaHT");
                    _MaHT = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaHT");
                    OnMaHTChanged();
                }
            }
        }
        private global::System.String _MaHT;
        partial void OnMaHTChanging(global::System.String value);
        partial void OnMaHTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DiemDi
        {
            get
            {
                return _DiemDi;
            }
            set
            {
                OnDiemDiChanging(value);
                ReportPropertyChanging("DiemDi");
                _DiemDi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DiemDi");
                OnDiemDiChanged();
            }
        }
        private global::System.String _DiemDi;
        partial void OnDiemDiChanging(global::System.String value);
        partial void OnDiemDiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DiemDen
        {
            get
            {
                return _DiemDen;
            }
            set
            {
                OnDiemDenChanging(value);
                ReportPropertyChanging("DiemDen");
                _DiemDen = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DiemDen");
                OnDiemDenChanged();
            }
        }
        private global::System.String _DiemDen;
        partial void OnDiemDenChanging(global::System.String value);
        partial void OnDiemDenChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_ChuyenBay_HangTrinh", "ChuyenBay")]
        public EntityCollection<ChuyenBay> ChuyenBays
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChuyenBay>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_HangTrinh", "ChuyenBay");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChuyenBay>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_HangTrinh", "ChuyenBay", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLChuyenBayVaVeMayBayModel", Name="HanhKhach")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HanhKhach : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HanhKhach object.
        /// </summary>
        /// <param name="maHK">Initial value of the MaHK property.</param>
        /// <param name="maVe">Initial value of the MaVe property.</param>
        /// <param name="hoHK">Initial value of the HoHK property.</param>
        /// <param name="tenHK">Initial value of the TenHK property.</param>
        /// <param name="soDT">Initial value of the SoDT property.</param>
        public static HanhKhach CreateHanhKhach(global::System.String maHK, global::System.String maVe, global::System.String hoHK, global::System.String tenHK, global::System.String soDT)
        {
            HanhKhach hanhKhach = new HanhKhach();
            hanhKhach.MaHK = maHK;
            hanhKhach.MaVe = maVe;
            hanhKhach.HoHK = hoHK;
            hanhKhach.TenHK = tenHK;
            hanhKhach.SoDT = soDT;
            return hanhKhach;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaHK
        {
            get
            {
                return _MaHK;
            }
            set
            {
                if (_MaHK != value)
                {
                    OnMaHKChanging(value);
                    ReportPropertyChanging("MaHK");
                    _MaHK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaHK");
                    OnMaHKChanged();
                }
            }
        }
        private global::System.String _MaHK;
        partial void OnMaHKChanging(global::System.String value);
        partial void OnMaHKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaVe
        {
            get
            {
                return _MaVe;
            }
            set
            {
                OnMaVeChanging(value);
                ReportPropertyChanging("MaVe");
                _MaVe = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaVe");
                OnMaVeChanged();
            }
        }
        private global::System.String _MaVe;
        partial void OnMaVeChanging(global::System.String value);
        partial void OnMaVeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoHK
        {
            get
            {
                return _HoHK;
            }
            set
            {
                OnHoHKChanging(value);
                ReportPropertyChanging("HoHK");
                _HoHK = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HoHK");
                OnHoHKChanged();
            }
        }
        private global::System.String _HoHK;
        partial void OnHoHKChanging(global::System.String value);
        partial void OnHoHKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenHK
        {
            get
            {
                return _TenHK;
            }
            set
            {
                OnTenHKChanging(value);
                ReportPropertyChanging("TenHK");
                _TenHK = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TenHK");
                OnTenHKChanged();
            }
        }
        private global::System.String _TenHK;
        partial void OnTenHKChanging(global::System.String value);
        partial void OnTenHKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SoDT
        {
            get
            {
                return _SoDT;
            }
            set
            {
                OnSoDTChanging(value);
                ReportPropertyChanging("SoDT");
                _SoDT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SoDT");
                OnSoDTChanged();
            }
        }
        private global::System.String _SoDT;
        partial void OnSoDTChanging(global::System.String value);
        partial void OnSoDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_Ve_HanhKhach", "Ve")]
        public EntityCollection<Ve> Ves
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ve>("QLChuyenBayVaVeMayBayModel.FK_Ve_HanhKhach", "Ve");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ve>("QLChuyenBayVaVeMayBayModel.FK_Ve_HanhKhach", "Ve", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLChuyenBayVaVeMayBayModel", Name="LichBay")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LichBay : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LichBay object.
        /// </summary>
        /// <param name="maCB">Initial value of the MaCB property.</param>
        public static LichBay CreateLichBay(global::System.String maCB)
        {
            LichBay lichBay = new LichBay();
            lichBay.MaCB = maCB;
            return lichBay;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaCB
        {
            get
            {
                return _MaCB;
            }
            set
            {
                if (_MaCB != value)
                {
                    OnMaCBChanging(value);
                    ReportPropertyChanging("MaCB");
                    _MaCB = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaCB");
                    OnMaCBChanged();
                }
            }
        }
        private global::System.String _MaCB;
        partial void OnMaCBChanging(global::System.String value);
        partial void OnMaCBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaMB
        {
            get
            {
                return _MaMB;
            }
            set
            {
                OnMaMBChanging(value);
                ReportPropertyChanging("MaMB");
                _MaMB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaMB");
                OnMaMBChanged();
            }
        }
        private global::System.String _MaMB;
        partial void OnMaMBChanging(global::System.String value);
        partial void OnMaMBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaHT
        {
            get
            {
                return _MaHT;
            }
            set
            {
                OnMaHTChanging(value);
                ReportPropertyChanging("MaHT");
                _MaHT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaHT");
                OnMaHTChanged();
            }
        }
        private global::System.String _MaHT;
        partial void OnMaHTChanging(global::System.String value);
        partial void OnMaHTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GioNgayBay
        {
            get
            {
                return _GioNgayBay;
            }
            set
            {
                OnGioNgayBayChanging(value);
                ReportPropertyChanging("GioNgayBay");
                _GioNgayBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GioNgayBay");
                OnGioNgayBayChanged();
            }
        }
        private Nullable<global::System.DateTime> _GioNgayBay;
        partial void OnGioNgayBayChanging(Nullable<global::System.DateTime> value);
        partial void OnGioNgayBayChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_LichBay_MayBay", "MayBay")]
        public MayBay MayBay
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MayBay>("QLChuyenBayVaVeMayBayModel.FK_LichBay_MayBay", "MayBay").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MayBay>("QLChuyenBayVaVeMayBayModel.FK_LichBay_MayBay", "MayBay").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MayBay> MayBayReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MayBay>("QLChuyenBayVaVeMayBayModel.FK_LichBay_MayBay", "MayBay");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MayBay>("QLChuyenBayVaVeMayBayModel.FK_LichBay_MayBay", "MayBay", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLChuyenBayVaVeMayBayModel", Name="MayBay")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MayBay : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MayBay object.
        /// </summary>
        /// <param name="maMB">Initial value of the MaMB property.</param>
        /// <param name="tenMB">Initial value of the TenMB property.</param>
        /// <param name="loaiMB">Initial value of the LoaiMB property.</param>
        /// <param name="soGheTG">Initial value of the SoGheTG property.</param>
        /// <param name="soGheDaDat">Initial value of the SoGheDaDat property.</param>
        /// <param name="tongSoGhe">Initial value of the TongSoGhe property.</param>
        public static MayBay CreateMayBay(global::System.String maMB, global::System.String tenMB, global::System.String loaiMB, global::System.String soGheTG, global::System.String soGheDaDat, global::System.String tongSoGhe)
        {
            MayBay mayBay = new MayBay();
            mayBay.MaMB = maMB;
            mayBay.TenMB = tenMB;
            mayBay.LoaiMB = loaiMB;
            mayBay.SoGheTG = soGheTG;
            mayBay.SoGheDaDat = soGheDaDat;
            mayBay.TongSoGhe = tongSoGhe;
            return mayBay;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaMB
        {
            get
            {
                return _MaMB;
            }
            set
            {
                if (_MaMB != value)
                {
                    OnMaMBChanging(value);
                    ReportPropertyChanging("MaMB");
                    _MaMB = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaMB");
                    OnMaMBChanged();
                }
            }
        }
        private global::System.String _MaMB;
        partial void OnMaMBChanging(global::System.String value);
        partial void OnMaMBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenMB
        {
            get
            {
                return _TenMB;
            }
            set
            {
                OnTenMBChanging(value);
                ReportPropertyChanging("TenMB");
                _TenMB = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TenMB");
                OnTenMBChanged();
            }
        }
        private global::System.String _TenMB;
        partial void OnTenMBChanging(global::System.String value);
        partial void OnTenMBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoaiMB
        {
            get
            {
                return _LoaiMB;
            }
            set
            {
                OnLoaiMBChanging(value);
                ReportPropertyChanging("LoaiMB");
                _LoaiMB = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoaiMB");
                OnLoaiMBChanged();
            }
        }
        private global::System.String _LoaiMB;
        partial void OnLoaiMBChanging(global::System.String value);
        partial void OnLoaiMBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SoGheTG
        {
            get
            {
                return _SoGheTG;
            }
            set
            {
                OnSoGheTGChanging(value);
                ReportPropertyChanging("SoGheTG");
                _SoGheTG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SoGheTG");
                OnSoGheTGChanged();
            }
        }
        private global::System.String _SoGheTG;
        partial void OnSoGheTGChanging(global::System.String value);
        partial void OnSoGheTGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SoGheDaDat
        {
            get
            {
                return _SoGheDaDat;
            }
            set
            {
                OnSoGheDaDatChanging(value);
                ReportPropertyChanging("SoGheDaDat");
                _SoGheDaDat = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SoGheDaDat");
                OnSoGheDaDatChanged();
            }
        }
        private global::System.String _SoGheDaDat;
        partial void OnSoGheDaDatChanging(global::System.String value);
        partial void OnSoGheDaDatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TongSoGhe
        {
            get
            {
                return _TongSoGhe;
            }
            set
            {
                OnTongSoGheChanging(value);
                ReportPropertyChanging("TongSoGhe");
                _TongSoGhe = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TongSoGhe");
                OnTongSoGheChanged();
            }
        }
        private global::System.String _TongSoGhe;
        partial void OnTongSoGheChanging(global::System.String value);
        partial void OnTongSoGheChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_ChuyenBay_MayBay", "ChuyenBay")]
        public EntityCollection<ChuyenBay> ChuyenBays
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChuyenBay>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_MayBay", "ChuyenBay");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChuyenBay>("QLChuyenBayVaVeMayBayModel.FK_ChuyenBay_MayBay", "ChuyenBay", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_LichBay_MayBay", "LichBay")]
        public EntityCollection<LichBay> LichBays
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LichBay>("QLChuyenBayVaVeMayBayModel.FK_LichBay_MayBay", "LichBay");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LichBay>("QLChuyenBayVaVeMayBayModel.FK_LichBay_MayBay", "LichBay", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLChuyenBayVaVeMayBayModel", Name="Ve")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ve : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ve object.
        /// </summary>
        /// <param name="maVe">Initial value of the MaVe property.</param>
        /// <param name="maHK">Initial value of the MaHK property.</param>
        /// <param name="maCB">Initial value of the MaCB property.</param>
        /// <param name="ngayGioBay">Initial value of the NgayGioBay property.</param>
        /// <param name="ngayGioBan">Initial value of the NgayGioBan property.</param>
        /// <param name="giaVe">Initial value of the GiaVe property.</param>
        public static Ve CreateVe(global::System.String maVe, global::System.String maHK, global::System.String maCB, global::System.DateTime ngayGioBay, global::System.DateTime ngayGioBan, global::System.Decimal giaVe)
        {
            Ve ve = new Ve();
            ve.MaVe = maVe;
            ve.MaHK = maHK;
            ve.MaCB = maCB;
            ve.NgayGioBay = ngayGioBay;
            ve.NgayGioBan = ngayGioBan;
            ve.GiaVe = giaVe;
            return ve;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaVe
        {
            get
            {
                return _MaVe;
            }
            set
            {
                if (_MaVe != value)
                {
                    OnMaVeChanging(value);
                    ReportPropertyChanging("MaVe");
                    _MaVe = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaVe");
                    OnMaVeChanged();
                }
            }
        }
        private global::System.String _MaVe;
        partial void OnMaVeChanging(global::System.String value);
        partial void OnMaVeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaHK
        {
            get
            {
                return _MaHK;
            }
            set
            {
                OnMaHKChanging(value);
                ReportPropertyChanging("MaHK");
                _MaHK = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaHK");
                OnMaHKChanged();
            }
        }
        private global::System.String _MaHK;
        partial void OnMaHKChanging(global::System.String value);
        partial void OnMaHKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaCB
        {
            get
            {
                return _MaCB;
            }
            set
            {
                OnMaCBChanging(value);
                ReportPropertyChanging("MaCB");
                _MaCB = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaCB");
                OnMaCBChanged();
            }
        }
        private global::System.String _MaCB;
        partial void OnMaCBChanging(global::System.String value);
        partial void OnMaCBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayGioBay
        {
            get
            {
                return _NgayGioBay;
            }
            set
            {
                OnNgayGioBayChanging(value);
                ReportPropertyChanging("NgayGioBay");
                _NgayGioBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayGioBay");
                OnNgayGioBayChanged();
            }
        }
        private global::System.DateTime _NgayGioBay;
        partial void OnNgayGioBayChanging(global::System.DateTime value);
        partial void OnNgayGioBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayGioBan
        {
            get
            {
                return _NgayGioBan;
            }
            set
            {
                OnNgayGioBanChanging(value);
                ReportPropertyChanging("NgayGioBan");
                _NgayGioBan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayGioBan");
                OnNgayGioBanChanged();
            }
        }
        private global::System.DateTime _NgayGioBan;
        partial void OnNgayGioBanChanging(global::System.DateTime value);
        partial void OnNgayGioBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoiBan
        {
            get
            {
                return _NoiBan;
            }
            set
            {
                OnNoiBanChanging(value);
                ReportPropertyChanging("NoiBan");
                _NoiBan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoiBan");
                OnNoiBanChanged();
            }
        }
        private global::System.String _NoiBan;
        partial void OnNoiBanChanging(global::System.String value);
        partial void OnNoiBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GiaVe
        {
            get
            {
                return _GiaVe;
            }
            set
            {
                OnGiaVeChanging(value);
                ReportPropertyChanging("GiaVe");
                _GiaVe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GiaVe");
                OnGiaVeChanged();
            }
        }
        private global::System.Decimal _GiaVe;
        partial void OnGiaVeChanging(global::System.Decimal value);
        partial void OnGiaVeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_Ve_ChuyenBay", "ChuyenBay")]
        public ChuyenBay ChuyenBay
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChuyenBay>("QLChuyenBayVaVeMayBayModel.FK_Ve_ChuyenBay", "ChuyenBay").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChuyenBay>("QLChuyenBayVaVeMayBayModel.FK_Ve_ChuyenBay", "ChuyenBay").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ChuyenBay> ChuyenBayReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChuyenBay>("QLChuyenBayVaVeMayBayModel.FK_Ve_ChuyenBay", "ChuyenBay");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ChuyenBay>("QLChuyenBayVaVeMayBayModel.FK_Ve_ChuyenBay", "ChuyenBay", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_DoiTraVe_Ve", "DoiTraVe")]
        public EntityCollection<DoiTraVe> DoiTraVes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DoiTraVe>("QLChuyenBayVaVeMayBayModel.FK_DoiTraVe_Ve", "DoiTraVe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DoiTraVe>("QLChuyenBayVaVeMayBayModel.FK_DoiTraVe_Ve", "DoiTraVe", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLChuyenBayVaVeMayBayModel", "FK_Ve_HanhKhach", "HanhKhach")]
        public HanhKhach HanhKhach
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HanhKhach>("QLChuyenBayVaVeMayBayModel.FK_Ve_HanhKhach", "HanhKhach").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HanhKhach>("QLChuyenBayVaVeMayBayModel.FK_Ve_HanhKhach", "HanhKhach").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HanhKhach> HanhKhachReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HanhKhach>("QLChuyenBayVaVeMayBayModel.FK_Ve_HanhKhach", "HanhKhach");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HanhKhach>("QLChuyenBayVaVeMayBayModel.FK_Ve_HanhKhach", "HanhKhach", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
